"""RTL simulation verification tool for PLENA.

Verifies HBM and VRAM contents after RTL simulation by comparing
against golden expected results.

Usage:
    python -m verification.verify_rtl_sim --workload-dir /path/to/build

The workload directory should contain:
    - verification_params.json: Parameters for verification
    - golden_result.txt or golden_result.pt: Expected output
    - hbm_result.mem: HBM dump from simulation (generated by Verilator)
"""

import argparse
import json
import re
import sys
from pathlib import Path

import numpy as np
import torch


def parse_hbm_result_file(filepath: Path) -> dict[int, int]:
    """Parse HBM result file - simple sequential format.

    File format:
        0xDATA_ROW_0
        0xDATA_ROW_1
        ...

    Args:
        filepath: Path to hbm_result.mem file

    Returns:
        Dictionary mapping row index to 256-bit data value
    """
    data = {}
    line_num = 0

    with open(filepath) as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("//"):
                continue

            # Parse hex data: 0x<hex>
            if line.startswith("0x") or line.startswith("0X"):
                data[line_num] = int(line, 16)
                line_num += 1

    return data


def read_hbm_elements_and_scales(
    hbm_data: dict[int, int],
    start_addr: int,
    num_elements: int,
    row_width: int = 256,  # HBM row width (256 bits)
    mx_element_width: int = 8,  # Width per MX element (8 bits for 4+3+1)
    mx_scale_width: int = 8,  # Width per MX scale (8 bits)
    block_size: int = 8,  # Elements per block
    scale_offset: int | None = None,  # Byte offset from elements to scales
) -> tuple[np.ndarray, np.ndarray]:
    """Extract elements and scales from unified HBM data.

    Args:
        hbm_data: Parsed HBM data {row_index: 256-bit value}
        start_addr: Starting byte address
        num_elements: Number of elements to read
        row_width: HBM row width in bits (256)
        mx_element_width: Width of each MX element in bits
        mx_scale_width: Width of each MX scale in bits
        block_size: Elements per scale block
        scale_offset: Byte offset from elements to scales

    Returns:
        Tuple of (elements array, scales array)
    """
    if (
        start_addr < 0
        or num_elements <= 0
        or row_width <= 0
        or row_width % 8
        or mx_element_width <= 0
        or mx_element_width % 8
        or mx_scale_width <= 0
        or mx_scale_width % 8
        or block_size <= 0
        or (scale_offset is not None and scale_offset < 0)
    ):
        raise ValueError(
            "HBM extraction dimensions must be positive, byte-aligned, and in range"
        )
    bytes_per_row = row_width // 8  # 32 bytes per row

    # Extract elements
    elements = []
    for i in range(num_elements):
        byte_addr = start_addr + i * (mx_element_width // 8)
        row_idx = byte_addr // bytes_per_row
        byte_offset = byte_addr % bytes_per_row
        bit_offset = byte_offset * 8

        if row_idx not in hbm_data:
            raise ValueError(f"HBM element source row is missing: {row_idx}")
        row_data = hbm_data[row_idx]
        element = (row_data >> bit_offset) & ((1 << mx_element_width) - 1)
        elements.append(element)

    # Extract scales
    num_blocks = (num_elements + block_size - 1) // block_size
    scales = []
    scale_start_addr = (
        (start_addr + scale_offset)
        if scale_offset
        else (start_addr + num_elements)
    )

    for i in range(num_blocks):
        byte_addr = scale_start_addr + i * (mx_scale_width // 8)
        row_idx = byte_addr // bytes_per_row
        byte_offset = byte_addr % bytes_per_row
        bit_offset = byte_offset * 8

        if row_idx not in hbm_data:
            raise ValueError(f"HBM scale source row is missing: {row_idx}")
        row_data = hbm_data[row_idx]
        scale = (row_data >> bit_offset) & ((1 << mx_scale_width) - 1)
        scales.append(scale)

    return np.array(elements, dtype=np.uint8), np.array(scales, dtype=np.uint8)


def mx_to_float(
    elements: np.ndarray,
    scales: np.ndarray,
    exp_width: int = 4,
    man_width: int = 3,
    scale_width: int = 8,
    block_size: int = 8,
) -> np.ndarray:
    """Convert MXFP format data to float.

    MXFP format: Each element has [sign(1)][exponent(exp_width)][mantissa(man_width)]
    with a shared block scale.

    Args:
        elements: Raw element data (uint8 array)
        scales: Raw scale data (uint8 array)
        exp_width: Exponent width for elements
        man_width: Mantissa width for elements
        scale_width: Scale exponent width
        block_size: Elements per block

    Returns:
        Float array of converted values
    """
    values = []
    1 << (exp_width + man_width)
    ((1 << exp_width) - 1) << man_width
    man_mask = (1 << man_width) - 1
    bias = (1 << (exp_width - 1)) - 1 if exp_width > 0 else 0
    scale_bias = 127  # E8M0 scale bias

    for i, elem in enumerate(elements):
        block_idx = i // block_size
        scale = scales[block_idx] if block_idx < len(scales) else 0

        # Parse element
        sign = (elem >> (exp_width + man_width)) & 1
        exp = (elem >> man_width) & ((1 << exp_width) - 1)
        man = elem & man_mask

        # Convert element to float
        if exp == 0:
            # Subnormal or zero
            if man == 0:
                elem_val = 0.0
            else:
                elem_val = (
                    ((-1) ** int(sign))
                    * (man / (2**man_width))
                    * (2 ** (1 - bias))
                )
        elif exp == (1 << exp_width) - 1:
            # Inf/NaN
            elem_val = float("inf") if man == 0 else float("nan")
            if sign:
                elem_val = -elem_val
        else:
            # Normal
            elem_val = (
                ((-1) ** int(sign))
                * (1 + man / (2**man_width))
                * (2 ** (exp - bias))
            )

        # Apply scale (E8M0 format)
        scale_val = 2 ** (scale - scale_bias)
        values.append(elem_val * scale_val)

    return np.array(values, dtype=np.float32)


def mxint_to_float(
    elements: np.ndarray,
    scales: np.ndarray,
    int_width: int = 8,
    scale_width: int = 8,
    block_size: int = 8,
) -> np.ndarray:
    """Convert MXINT format data to float.

    MXINT format: Each element has [sign(1)][magnitude(int_width-1)]
    with a shared block scale (exponent).

    Value = (-1)^sign * (magnitude / 2^(int_width-1)) * 2^(scale - bias)

    Args:
        elements: Raw element data (uint8 array)
        scales: Raw scale data (uint8 array)
        int_width: Total integer width including sign bit (default: 8)
        scale_width: Scale exponent width (default: 8)
        block_size: Elements per block (default: 8)

    Returns:
        Float array of converted values
    """
    values = []
    magnitude_bits = int_width - 1
    magnitude_mask = (1 << magnitude_bits) - 1
    scale_bias = (1 << (scale_width - 1)) - 1  # 127 for 8-bit scale

    for i, elem in enumerate(elements):
        block_idx = i // block_size
        scale = scales[block_idx] if block_idx < len(scales) else scale_bias

        # Parse element: [sign(1)][magnitude(int_width-1)]
        sign = (elem >> magnitude_bits) & 1
        magnitude = elem & magnitude_mask

        # Convert to float
        # Normalized mantissa = magnitude / 2^magnitude_bits (in range [0, 1))
        normalized_mantissa = magnitude / (1 << magnitude_bits)

        # Apply scale: 2^(scale - bias)
        scale_val = 2 ** (int(scale) - scale_bias)

        elem_val = normalized_mantissa * scale_val
        if sign:
            elem_val = -elem_val

        values.append(elem_val)

    return np.array(values, dtype=np.float32)


def compare_results(
    simulated: np.ndarray,
    golden: np.ndarray,
    atol: float = 0.1,
    rtol: float = 0.1,
) -> dict:
    """Compare simulated results against golden reference.

    Args:
        simulated: Simulated output array
        golden: Golden reference array
        atol: Absolute tolerance
        rtol: Relative tolerance

    Returns:
        Dictionary with comparison metrics
    """
    simulated = np.asarray(simulated).reshape(-1)
    golden = np.asarray(golden).reshape(-1)
    simulated_count = simulated.size
    golden_count = golden.size
    if simulated_count == 0 or simulated_count != golden_count:
        return {
            "error": (
                f"comparison cardinality mismatch: simulated={simulated_count}, golden={golden_count}"
            ),
            "mse": float("inf"),
            "mae": float("inf"),
            "max_error": float("inf"),
            "match_rate": 0.0,
            "passed": False,
            "num_compared": 0,
            "simulated_count": int(simulated_count),
            "golden_count": int(golden_count),
            "atol": atol,
            "rtol": rtol,
        }

    # Convert to tensors for comparison
    sim_t = torch.from_numpy(simulated).float()
    gold_t = torch.from_numpy(golden).float()

    # Compute errors
    errors = torch.abs(sim_t - gold_t)

    # Metrics
    mse = torch.mean((sim_t - gold_t) ** 2).item()
    mae = torch.mean(errors).item()
    max_error = torch.max(errors).item()

    # Allclose check
    tolerance = atol + rtol * torch.abs(gold_t)
    within_tol = errors <= tolerance
    match_rate = torch.sum(within_tol).item() / len(errors) * 100

    # Pass criteria
    passed = match_rate >= 90.0

    return {
        "mse": mse,
        "mae": mae,
        "max_error": max_error,
        "match_rate": match_rate,
        "passed": passed,
        "num_compared": int(simulated_count),
        "atol": atol,
        "rtol": rtol,
    }


def parse_golden_file(filepath: Path) -> np.ndarray:
    """Parse golden result from .txt or .pt file.

    Args:
        filepath: Path to golden result file

    Returns:
        Flattened numpy array of golden values
    """
    if filepath.suffix == ".pt":
        tensor = torch.load(filepath)
        return tensor.float().numpy().flatten()

    # Parse text file
    with open(filepath) as f:
        content = f.read()

    # Find "Original Output:" section
    match = re.search(r"Original Output:\s*\[(.*?)\]", content, re.DOTALL)
    if not match:
        # Try tensor() format
        match = re.search(r"tensor\(\[(.*?)\]", content, re.DOTALL)

    if not match:
        raise ValueError("Could not find output values in golden file")

    values_text = match.group(1)
    values = []
    for line in values_text.strip().split("\n"):
        line = line.strip().strip(",").strip("[").strip("]")
        if not line:
            continue
        for val_str in line.replace(",", " ").split():
            try:
                val = float(val_str)
                values.append(val)
            except ValueError:
                continue

    return np.array(values, dtype=np.float32)


def verify_hbm(
    workload_dir: Path,
    params: dict,
    verbose: bool = True,
    save_translated: bool = True,
) -> dict:
    """Verify HBM contents against golden result.

    Supports both MXFP and MXINT formats based on params["mx_format"].
    Supports configurable row-based comparison via params.

    Args:
        workload_dir: Path to workload build directory
        params: Verification parameters (should include "mx_format" for MXINT)
            - golden_hbm_file: Optional separate golden file for HBM (default: golden_result.pt)
            - hbm_compare_start_row: Start row for comparison (default: 0)
            - hbm_compare_num_rows: Number of rows to compare (default: all)
        verbose: Print detailed output
        save_translated: Save translated FP values to file for debugging

    Returns:
        Verification result dictionary
    """
    hbm_result_file = workload_dir / "hbm_result.mem"

    # Use separate HBM golden file if specified, else fall back to unified golden
    golden_hbm_filename = params.get("golden_hbm_file", "golden_result.pt")
    golden_file = workload_dir / golden_hbm_filename
    if not golden_file.exists():
        golden_file = workload_dir / golden_hbm_filename.replace(".pt", ".txt")
    if not golden_file.exists():
        # Fall back to unified golden
        golden_file = workload_dir / "golden_result.pt"
        if not golden_file.exists():
            golden_file = workload_dir / "golden_result.txt"

    if not hbm_result_file.exists():
        return {"error": f"HBM result file not found: {hbm_result_file}"}

    if not golden_file.exists():
        return {"error": f"Golden file not found: {golden_file}"}

    # Parse HBM result
    hbm_data = parse_hbm_result_file(hbm_result_file)

    # Extract relevant parameters
    start_addr = params.get("result_hbm_start_byte", 0)
    num_elements = params.get("num_elements", 0)
    scale_width = params.get("scale_width", 8)
    block_size = params.get("block_size", 8)
    scale_offset = params.get("scale_offset")
    try:
        start_addr = int(start_addr)
        num_elements = int(num_elements)
        scale_width = int(scale_width)
        block_size = int(block_size)
        if scale_offset is not None:
            scale_offset = int(scale_offset)
    except (TypeError, ValueError):
        return {
            "type": "hbm",
            "passed": False,
            "error": "HBM dimensions must be integers",
        }

    # Determine format: MXINT or MXFP
    mx_format = params.get("mx_format", "mxfp").lower()

    if mx_format == "mxint":
        int_width = int(
            params.get("man_width", 8)
        )  # For MXINT, man_width is the int_width
        mx_element_width = int_width
    else:
        exp_width = int(params.get("exp_width", 4))
        man_width = int(params.get("man_width", 3))
        mx_element_width = 1 + exp_width + man_width  # sign + exp + man

    # Extract elements and scales
    try:
        elements, scales = read_hbm_elements_and_scales(
            hbm_data,
            start_addr=start_addr,
            num_elements=num_elements,
            mx_element_width=mx_element_width,
            mx_scale_width=scale_width,
            block_size=block_size,
            scale_offset=scale_offset,
        )
    except (TypeError, ValueError) as error:
        return {"type": "hbm", "passed": False, "error": str(error)}

    # Convert to float based on format
    if mx_format == "mxint":
        simulated_all = mxint_to_float(
            elements,
            scales,
            int_width=int_width,
            scale_width=scale_width,
            block_size=block_size,
        )
        format_info = (
            f"MXINT (int_width={int_width}, scale_width={scale_width})"
        )
    else:
        simulated_all = mx_to_float(
            elements,
            scales,
            exp_width=exp_width,
            man_width=man_width,
            scale_width=scale_width,
            block_size=block_size,
        )
        format_info = (
            f"MXFP (exp={exp_width}, man={man_width}, scale={scale_width})"
        )
    if simulated_all.size != num_elements:
        return {
            "type": "hbm",
            "passed": False,
            "error": (
                f"HBM element cardinality mismatch: expected={num_elements}, extracted={simulated_all.size}"
            ),
        }

    # Apply row-based comparison filter if specified
    hbm_elements_per_row = params.get(
        "hbm_elements_per_row", 32
    )  # Default: 32 elements per 256-bit row
    hbm_compare_start_row = params.get("hbm_compare_start_row", 0)
    hbm_compare_num_rows = params.get("hbm_compare_num_rows", None)
    try:
        hbm_elements_per_row = int(hbm_elements_per_row)
        hbm_compare_start_row = int(hbm_compare_start_row)
        if hbm_compare_num_rows is not None:
            hbm_compare_num_rows = int(hbm_compare_num_rows)
    except (TypeError, ValueError):
        return {
            "type": "hbm",
            "passed": False,
            "error": "HBM comparison dimensions must be integers",
        }
    if hbm_elements_per_row <= 0 or hbm_compare_start_row < 0:
        return {
            "type": "hbm",
            "passed": False,
            "error": "HBM comparison dimensions must be positive and the start row non-negative",
        }
    hbm_total_rows = params.get(
        "hbm_total_rows",
        (num_elements + hbm_elements_per_row - 1) // hbm_elements_per_row,
    )

    # Calculate element range to compare
    start_elem_idx = hbm_compare_start_row * hbm_elements_per_row
    if hbm_compare_num_rows is None:
        expected_compared_elements = len(simulated_all) - start_elem_idx
    else:
        if hbm_compare_num_rows <= 0:
            return {
                "type": "hbm",
                "passed": False,
                "error": "HBM comparison row count must be positive",
            }
        expected_compared_elements = hbm_compare_num_rows * hbm_elements_per_row
    end_elem_idx = start_elem_idx + expected_compared_elements
    if expected_compared_elements <= 0 or end_elem_idx > len(simulated_all):
        return {
            "type": "hbm",
            "passed": False,
            "error": (
                "HBM comparison window is outside the extracted elements: "
                f"start={start_elem_idx}, count={expected_compared_elements}, extracted={len(simulated_all)}"
            ),
        }

    # Filter to only the rows we want to compare
    simulated = simulated_all[start_elem_idx:end_elem_idx]
    if simulated.size != expected_compared_elements:
        return {
            "type": "hbm",
            "passed": False,
            "error": (
                "HBM comparison cardinality mismatch: "
                f"expected={expected_compared_elements}, extracted={simulated.size}"
            ),
        }

    if verbose and (
        hbm_compare_start_row > 0 or hbm_compare_num_rows is not None
    ):
        actual_rows = (
            end_elem_idx - start_elem_idx + hbm_elements_per_row - 1
        ) // hbm_elements_per_row
        print("\nHBM Comparison Filter:")
        print(
            f"  Comparing rows {hbm_compare_start_row} to {hbm_compare_start_row + actual_rows - 1} (of {hbm_total_rows} total)"
        )
        print(
            f"  Elements {start_elem_idx} to {end_elem_idx - 1} (of {len(simulated_all)} total)"
        )

    # Save translated FP values to file
    if save_translated:
        fp_output_file = workload_dir / "hbm_result.fp.txt"
        # Use HBM row structure for formatting (matches .mem file rows)
        hbm_row_elements = params.get("hbm_elements_per_row", 32)
        total_hbm_rows = (
            len(simulated_all) + hbm_row_elements - 1
        ) // hbm_row_elements

        with open(fp_output_file, "w") as f:
            f.write("# HBM Result - Translated to Floating Point\n")
            f.write(f"# Source: {hbm_result_file}\n")
            f.write(f"# Format: {format_info}\n")
            f.write(
                f"# Rows: 0 to {total_hbm_rows - 1} (matching .mem file rows)\n"
            )
            f.write(f"# Elements per row: {hbm_row_elements}\n")
            f.write(f"# Total elements: {len(simulated_all)}\n")
            f.write("#\n")

            # Write translated FP values organized by HBM row (matching .mem file)
            for row_idx in range(total_hbm_rows):
                start_idx = row_idx * hbm_row_elements
                end_idx = min(start_idx + hbm_row_elements, len(simulated_all))
                row_values = simulated_all[start_idx:end_idx]
                f.write(f"Row {row_idx:4d}:")
                for v in row_values:
                    f.write(f" {v:12.6f}")
                f.write("\n")

        if verbose:
            print(f"\nTranslated HBM saved to: {fp_output_file}")

    # Parse golden and apply same row filtering
    golden_all = parse_golden_file(golden_file)

    if golden_all.size == simulated_all.size:
        golden = golden_all[start_elem_idx:end_elem_idx]
    elif golden_all.size == expected_compared_elements:
        golden = golden_all
    else:
        return {
            "type": "hbm",
            "passed": False,
            "error": (
                "HBM golden cardinality mismatch: "
                f"expected comparison={expected_compared_elements} or full={simulated_all.size}, "
                f"golden={golden_all.size}"
            ),
        }
    if golden.size != expected_compared_elements:
        return {
            "type": "hbm",
            "passed": False,
            "error": (
                "HBM golden comparison cardinality mismatch: "
                f"expected={expected_compared_elements}, golden={golden.size}"
            ),
        }

    # Show comparison of first elements before full comparison
    if verbose:
        print("\n" + "=" * 60)
        print("HBM Data Comparison (first 16 elements)")
        print("=" * 60)
        print(f"{'Index':<6} {'Simulated':<14} {'Golden':<14} {'Diff':<14}")
        print("-" * 60)
        for i in range(min(16, len(simulated), len(golden))):
            diff = simulated[i] - golden[i]
            print(
                f"{i:<6} {simulated[i]:<14.6f} {golden[i]:<14.6f} {diff:<14.6f}"
            )

    # Compare
    result = compare_results(simulated, golden)
    result["type"] = "hbm"
    result["mx_format"] = mx_format

    if verbose:
        print("\n" + "=" * 60)
        print("HBM Verification Results")
        print("=" * 60)
        print(f"  Format: {format_info}")
        print(f"  Elements compared: {result['num_compared']}")
        print(f"  MSE: {result['mse']:.6e}")
        print(f"  MAE: {result['mae']:.6e}")
        print(f"  Max Error: {result['max_error']:.6f}")
        print(f"  Match Rate: {result['match_rate']:.2f}%")
        print(f"  Status: {'PASSED' if result['passed'] else 'FAILED'}")
        print("=" * 60)

    # Add file path to result
    if save_translated:
        result["fp_output_file"] = str(workload_dir / "hbm_result.fp.txt")

    return result


def verify_hbm_rows(
    workload_dir: Path,
    params: dict,
    rows_to_check: list[int] | None = None,
    expected_values: str = "zeros",
    verbose: bool = True,
    atol: float = 0.01,
) -> dict:
    """Verify specific HBM rows against expected values.

    Configurable row-based verification that checks specific rows
    and compares against expected patterns (zeros, custom values, etc.)

    Args:
        workload_dir: Path to workload build directory
        params: Verification parameters
        rows_to_check: List of row indices to check (default: [0, 1] for first two rows)
        expected_values: Expected pattern - "zeros" or list of expected FP values
        verbose: Print detailed output
        atol: Absolute tolerance for comparison

    Returns:
        Verification result dictionary
    """
    if rows_to_check is None:
        rows_to_check = [0, 1]  # Default: check first two rows

    hbm_result_file = workload_dir / "hbm_result.mem"

    if not hbm_result_file.exists():
        return {"error": f"HBM result file not found: {hbm_result_file}"}

    # Parse HBM result file
    hbm_rows = []
    with open(hbm_result_file) as f:
        for line in f:
            line = line.strip()
            if line.startswith("0x") or line.startswith("0X"):
                hbm_rows.append(int(line, 16))

    # Get format parameters
    mx_format = params.get("mx_format", "mxint").lower()
    scale_width = params.get("scale_width", 8)
    params.get("block_size", 8)
    row_width = 256  # bits per row

    if mx_format == "mxint":
        element_width = params.get("man_width", 8)
    else:
        exp_width = params.get("exp_width", 4)
        man_width = params.get("man_width", 3)
        element_width = 1 + exp_width + man_width

    elements_per_row = row_width // element_width
    format_info = f"{mx_format.upper()} (element_width={element_width})"

    if verbose:
        print("\n" + "=" * 70)
        print("HBM Row-based Verification")
        print("=" * 70)
        print(f"Format: {format_info}")
        print(f"Rows to check: {rows_to_check}")
        print(f"Elements per row: {elements_per_row}")
        print(f"Expected: {expected_values}")
        print()

    all_passed = True
    results_per_row = []

    for row_idx in rows_to_check:
        if row_idx >= len(hbm_rows):
            results_per_row.append(
                {"row": row_idx, "error": "Row index out of range"}
            )
            all_passed = False
            continue

        row_value = hbm_rows[row_idx]

        # Extract elements from this row
        elements = []
        for i in range(elements_per_row):
            elem = (row_value >> (i * element_width)) & (
                (1 << element_width) - 1
            )
            elements.append(elem)

        # Get scale for this row (assume scale is in a separate region or use default)
        # For simplicity, use bias value as scale (meaning exponent = 0)
        (1 << (scale_width - 1)) - 1  # 127 for 8-bit

        # Convert elements to float
        fp_values = []
        for elem in elements:
            if mx_format == "mxint":
                # MXINT: [sign(1)][magnitude(width-1)]
                magnitude_bits = element_width - 1
                sign = (elem >> magnitude_bits) & 1
                magnitude = elem & ((1 << magnitude_bits) - 1)
                normalized = magnitude / (1 << magnitude_bits)
                # Use scale from data if available, otherwise default
                scale_exp = 0  # Assume scale gives exp=0 for now
                fp_val = normalized * (2**scale_exp)
                if sign:
                    fp_val = -fp_val
            else:
                # MXFP: [sign(1)][exp][man]
                sign = (elem >> (exp_width + man_width)) & 1
                exp = (elem >> man_width) & ((1 << exp_width) - 1)
                man = elem & ((1 << man_width) - 1)
                bias = (1 << (exp_width - 1)) - 1
                if exp == 0:
                    fp_val = (
                        0.0
                        if man == 0
                        else (man / (2**man_width)) * (2 ** (1 - bias))
                    )
                else:
                    fp_val = (1 + man / (2**man_width)) * (2 ** (exp - bias))
                if sign:
                    fp_val = -fp_val

            fp_values.append(fp_val)

        # Compare with expected
        if expected_values == "zeros":
            expected = [0.0] * len(fp_values)
        elif isinstance(expected_values, list):
            expected = expected_values
        else:
            expected = [0.0] * len(fp_values)

        # Check if values match
        errors = []
        for i, (actual, exp) in enumerate(zip(fp_values, expected)):
            if abs(actual - exp) > atol:
                errors.append((i, actual, exp))

        row_passed = len(errors) == 0

        row_result = {
            "row": row_idx,
            "passed": row_passed,
            "num_elements": len(fp_values),
            "num_errors": len(errors),
            "fp_values": fp_values[:16],  # First 16 for display
            "raw_hex": f"0x{row_value:064X}"[:40] + "...",
        }
        results_per_row.append(row_result)

        if not row_passed:
            all_passed = False

        if verbose:
            status = "PASS" if row_passed else "FAIL"
            print(f"Row {row_idx}: {status}")
            print(
                f"  Raw (first 128 bits): 0x{(row_value & ((1 << 128) - 1)):032X}"
            )
            print(
                f"  FP values (first 8): {[f'{v:.4f}' for v in fp_values[:8]]}"
            )
            if not row_passed:
                print(f"  Errors ({len(errors)} elements differ):")
                for idx, actual, exp in errors[:5]:  # Show first 5 errors
                    print(
                        f"    [{idx}] actual={actual:.6f}, expected={exp:.6f}"
                    )
            print()

    result = {
        "type": "hbm_rows",
        "passed": all_passed,
        "rows_checked": rows_to_check,
        "results_per_row": results_per_row,
        "expected": expected_values,
    }

    if verbose:
        print("=" * 70)
        print(f"Overall: {'PASSED' if all_passed else 'FAILED'}")
        print("=" * 70)

    return result


def parse_vector_result_file(
    filepath: Path, row_width_bits: int = 192
) -> list[int]:
    """Parse vector SRAM result file.

    File format (hex values, one per line):
        DATA_ROW_0
        DATA_ROW_1
        ...

    Args:
        filepath: Path to vector_result.mem file
        row_width_bits: Width of each row in bits (default: 192 for VLEN=16, FP12)

    Returns:
        List of row data values (as integers)
    """
    data = []

    with open(filepath) as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("//"):
                continue

            # Parse hex data (with or without 0x prefix)
            try:
                if line.startswith("0x") or line.startswith("0X"):
                    data.append(int(line, 16))
                else:
                    data.append(int(line, 16))
            except ValueError:
                continue

    return data


def fp_to_float(
    element: int,
    exp_width: int = 6,
    man_width: int = 5,
) -> float:
    """Convert FP format element to float.

    Args:
        element: Raw element data (uint, with sign+exp+mant)
        exp_width: Exponent width (default: 6 for V_FP_EXP_WIDTH)
        man_width: Mantissa width (default: 5 for V_FP_MANT_WIDTH)

    Returns:
        Float value
    """
    total_width = 1 + exp_width + man_width
    mask = (1 << total_width) - 1
    element = element & mask

    # Extract fields
    sign = (element >> (exp_width + man_width)) & 1
    exp = (element >> man_width) & ((1 << exp_width) - 1)
    man = element & ((1 << man_width) - 1)

    bias = (1 << (exp_width - 1)) - 1  # bias = 31 for exp_width=6

    if exp == 0:
        # Subnormal or zero
        if man == 0:
            return 0.0
        # Subnormal: implicit leading 0
        val = (man / (2**man_width)) * (2 ** (1 - bias))
    elif exp == (1 << exp_width) - 1:
        # Inf/NaN
        if man == 0:
            return float("-inf") if sign else float("inf")
        return float("nan")
    else:
        # Normal: implicit leading 1
        val = (1 + man / (2**man_width)) * (2 ** (exp - bias))

    return -val if sign else val


def extract_fp_elements_from_row(
    row_data: int,
    num_elements: int = 16,
    exp_width: int = 6,
    man_width: int = 5,
) -> list[float]:
    """Extract FP elements from a row and convert to floats.

    Args:
        row_data: Row data as integer
        num_elements: Number of elements per row (VLEN)
        exp_width: FP exponent width
        man_width: FP mantissa width

    Returns:
        List of float values
    """
    element_width = 1 + exp_width + man_width
    element_mask = (1 << element_width) - 1

    values = []
    for i in range(num_elements):
        elem = (row_data >> (i * element_width)) & element_mask
        values.append(fp_to_float(elem, exp_width, man_width))

    return values


def save_vector_result_as_fp(
    filepath: Path,
    output_path: Path,
    vlen: int = 16,
    exp_width: int = 6,
    man_width: int = 5,
    start_row: int = 0,
    num_rows: int | None = None,
    format: str = "txt",
) -> Path:
    """Save vector_result.mem as floating point values to a file.

    Args:
        filepath: Path to vector_result.mem file
        output_path: Path to output file (without extension)
        vlen: Number of elements per row (VLEN)
        exp_width: FP exponent width (V_FP_EXP_WIDTH)
        man_width: FP mantissa width (V_FP_MANT_WIDTH)
        start_row: Starting row index
        num_rows: Number of rows to process (None = all)
        format: Output format - "txt" (human readable) or "mem" (one value per line)

    Returns:
        Path to the created output file
    """
    vram_data = parse_vector_result_file(filepath)
    if not vram_data:
        raise ValueError(f"No data found in {filepath}")

    total_rows = len(vram_data)
    end_row = (
        total_rows
        if num_rows is None
        else min(start_row + num_rows, total_rows)
    )

    element_width = 1 + exp_width + man_width
    fp_format = f"FP{element_width} (1s + {exp_width}e + {man_width}m)"

    # Extract all FP values
    all_fp_values = []
    row_fp_values = []
    for row_idx in range(start_row, end_row):
        row_floats = extract_fp_elements_from_row(
            vram_data[row_idx],
            num_elements=vlen,
            exp_width=exp_width,
            man_width=man_width,
        )
        row_fp_values.append((row_idx, row_floats))
        all_fp_values.extend(row_floats)

    # Determine output file path
    if format == "mem":
        out_file = output_path.with_suffix(".fp.mem")
    else:
        out_file = output_path.with_suffix(".fp.txt")

    with open(out_file, "w") as f:
        if format == "txt":
            # Human-readable format with header
            f.write("# Vector Result FP Values\n")
            f.write(f"# Source: {filepath}\n")
            f.write(f"# VLEN: {vlen}, Format: {fp_format}\n")
            f.write(
                f"# Rows: {start_row} to {end_row - 1} ({end_row - start_row} rows)\n"
            )
            f.write(f"# Total elements: {len(all_fp_values)}\n")
            f.write("#\n")
            for row_idx, row_floats in row_fp_values:
                f.write(f"Row {row_idx:4d}: ")
                f.write(" ".join(f"{v:12.6f}" for v in row_floats))
                f.write("\n")
        else:
            # .mem format - one value per line for easy parsing
            f.write(f"// Vector Result FP Values (VLEN={vlen}, {fp_format})\n")
            f.write(f"// Source: {filepath}\n")
            f.write(f"// Rows: {start_row} to {end_row - 1}\n")
            for row_idx, row_floats in row_fp_values:
                f.write(f"// Row {row_idx}\n")
                for v in row_floats:
                    f.write(f"{v:.8e}\n")

    return out_file


def verify_vram(
    workload_dir: Path,
    params: dict,
    verbose: bool = True,
    save_fp_result: bool = True,
) -> dict:
    """Verify VRAM (vector SRAM) contents against golden result.

    Uses configurable FP format from params or defaults to FP12
    (V_FP_EXP_WIDTH=6, V_FP_MANT_WIDTH=5).

    Args:
        workload_dir: Path to workload build directory
        params: Verification parameters (can include v_fp_exp_width, v_fp_man_width)
            - golden_vram_file: Optional separate golden file for VRAM (default: golden_result.pt)
            - vram_compare_start_row: Start row for comparison (default: 0)
            - vram_compare_num_rows: Number of rows to compare (default: all)
        verbose: Print detailed output
        save_fp_result: Save FP-converted values to file (default: True)

    Returns:
        Verification result dictionary
    """
    vram_result_file = workload_dir / "vector_result.mem"

    # Use separate VRAM golden file if specified, else fall back to unified golden
    golden_vram_filename = params.get("golden_vram_file", "golden_result.pt")
    golden_file = workload_dir / golden_vram_filename
    if not golden_file.exists():
        golden_file = workload_dir / golden_vram_filename.replace(".pt", ".txt")
    if not golden_file.exists():
        # Fall back to unified golden
        golden_file = workload_dir / "golden_result.pt"
        if not golden_file.exists():
            golden_file = workload_dir / "golden_result.txt"

    if not vram_result_file.exists():
        return {"error": f"VRAM result file not found: {vram_result_file}"}

    if vram_result_file.stat().st_size == 0:
        return {"error": "VRAM result file is empty (0 bytes)"}

    if not golden_file.exists():
        return {"error": f"Golden file not found: {golden_file}"}

    # Parse VRAM result
    vram_data = parse_vector_result_file(vram_result_file)

    if not vram_data:
        return {"error": "No data found in VRAM result file"}

    # FP precision - configurable via params, defaults from precision.svh
    exp_width = params.get("v_fp_exp_width", 6)
    man_width = params.get("v_fp_man_width", 5)
    vlen = params.get("row_dim", params.get("vlen", 16))

    # Extract parameters
    start_row = params.get("vram_start_row_idx", params.get("start_row_idx", 0))
    num_rows = params.get(
        "vram_num_rows", params.get("num_rows", len(vram_data))
    )
    try:
        vlen = int(vlen)
        start_row = int(start_row)
        num_rows = int(num_rows)
    except (TypeError, ValueError):
        return {
            "type": "vram",
            "passed": False,
            "error": "VRAM dimensions must be integers",
        }
    if vlen <= 0 or start_row < 0 or num_rows <= 0:
        return {
            "type": "vram",
            "passed": False,
            "error": "VRAM dimensions require VLEN and row count to be positive and the start row to be non-negative",
        }
    requested_end_row = start_row + num_rows
    if requested_end_row > len(vram_data):
        return {
            "type": "vram",
            "passed": False,
            "error": (
                "VRAM row cardinality mismatch: "
                f"requested rows {start_row}:{requested_end_row}, available rows={len(vram_data)}"
            ),
        }

    if verbose:
        print(f"\nVRAM file has {len(vram_data)} rows")
        print(f"Checking rows {start_row} to {start_row + num_rows - 1}")
        print(
            f"FP format: exp_width={exp_width}, man_width={man_width}, VLEN={vlen}"
        )

    # Extract all float values (row by row for saving)
    simulated_values = []
    row_fp_values = []
    for row_idx in range(start_row, requested_end_row):
        row_floats = extract_fp_elements_from_row(
            vram_data[row_idx],
            num_elements=vlen,
            exp_width=exp_width,
            man_width=man_width,
        )
        row_fp_values.append((row_idx, row_floats))
        simulated_values.extend(row_floats)

    expected_extracted_elements = num_rows * vlen
    if len(simulated_values) != expected_extracted_elements:
        return {
            "type": "vram",
            "passed": False,
            "error": (
                "VRAM element cardinality mismatch: "
                f"expected={expected_extracted_elements}, extracted={len(simulated_values)}"
            ),
        }

    simulated_all = np.array(simulated_values, dtype=np.float32)

    # Apply row-based comparison filter if specified
    vram_compare_start_row = params.get("vram_compare_start_row", 0)
    vram_compare_num_rows = params.get("vram_compare_num_rows", None)
    vram_total_rows = params.get("vram_total_rows", num_rows)
    try:
        vram_compare_start_row = int(vram_compare_start_row)
        if vram_compare_num_rows is None:
            vram_compare_num_rows = num_rows - vram_compare_start_row
        else:
            vram_compare_num_rows = int(vram_compare_num_rows)
    except (TypeError, ValueError):
        return {
            "type": "vram",
            "passed": False,
            "error": "VRAM comparison dimensions must be integers",
        }
    if (
        vram_compare_start_row < 0
        or vram_compare_num_rows <= 0
        or vram_compare_start_row + vram_compare_num_rows > num_rows
    ):
        return {
            "type": "vram",
            "passed": False,
            "error": (
                "VRAM comparison window is outside the extracted rows: "
                f"start={vram_compare_start_row}, rows={vram_compare_num_rows}, extracted_rows={num_rows}"
            ),
        }

    # Calculate element range to compare (relative to extracted data)
    compare_start_elem_idx = vram_compare_start_row * vlen
    expected_compared_elements = vram_compare_num_rows * vlen
    compare_end_elem_idx = compare_start_elem_idx + expected_compared_elements

    # Filter to only the rows we want to compare
    simulated = simulated_all[compare_start_elem_idx:compare_end_elem_idx]
    if simulated.size != expected_compared_elements:
        return {
            "type": "vram",
            "passed": False,
            "error": (
                "VRAM comparison cardinality mismatch: "
                f"expected={expected_compared_elements}, extracted={simulated.size}"
            ),
        }

    if verbose and (
        vram_compare_start_row > 0 or vram_compare_num_rows is not None
    ):
        actual_compare_rows = (
            compare_end_elem_idx - compare_start_elem_idx + vlen - 1
        ) // vlen
        print("\nVRAM Comparison Filter:")
        print(
            f"  Comparing rows {vram_compare_start_row} to {vram_compare_start_row + actual_compare_rows - 1} (of {vram_total_rows} total)"
        )
        print(
            f"  Elements {compare_start_elem_idx} to {compare_end_elem_idx - 1} (of {len(simulated_all)} total)"
        )

    # Save FP results to file if requested
    fp_output_file = None
    if save_fp_result:
        fp_output_file = workload_dir / "vector_result.fp.txt"
        element_width = 1 + exp_width + man_width
        fp_format = f"FP{element_width} (1s + {exp_width}e + {man_width}m)"

        with open(fp_output_file, "w") as f:
            f.write("# Vector Result FP Values\n")
            f.write(f"# Source: {vram_result_file}\n")
            f.write(f"# VLEN: {vlen}, Format: {fp_format}\n")
            f.write(f"# Rows: {start_row} to {start_row + num_rows - 1}\n")
            f.write(f"# Total elements: {len(simulated_values)}\n")
            f.write("#\n")
            for row_idx, row_floats in row_fp_values:
                f.write(f"Row {row_idx:4d}:")
                for v in row_floats:
                    f.write(f" {v:12.6f}")
                f.write("\n")

        if verbose:
            print(f"FP results saved to: {fp_output_file}")

    # Parse golden and apply same row filtering
    golden_all = parse_golden_file(golden_file)

    if golden_all.size != expected_extracted_elements:
        return {
            "type": "vram",
            "passed": False,
            "error": (
                f"VRAM golden cardinality mismatch: expected={expected_extracted_elements}, golden={golden_all.size}"
            ),
        }
    golden = golden_all[compare_start_elem_idx:compare_end_elem_idx]
    if golden.size != expected_compared_elements:
        return {
            "type": "vram",
            "passed": False,
            "error": (
                "VRAM golden comparison cardinality mismatch: "
                f"expected={expected_compared_elements}, golden={golden.size}"
            ),
        }

    # Compare
    result = compare_results(simulated, golden)
    result["type"] = "vram"
    result["rows_checked"] = num_rows
    result["rows_compared"] = vram_compare_num_rows
    result["fp_exp_width"] = exp_width
    result["fp_man_width"] = man_width
    result["vlen"] = vlen
    if fp_output_file:
        result["fp_output_file"] = str(fp_output_file)

    if verbose:
        print("\n" + "=" * 60)
        print("VRAM Verification Results")
        print("=" * 60)
        print(
            f"  FP Format: {1 + exp_width + man_width}-bit (1s + {exp_width}e + {man_width}m)"
        )
        print(f"  VLEN: {vlen}")
        print(f"  Rows checked: {result['rows_checked']}")
        print(f"  Elements compared: {result['num_compared']}")
        print(f"  MSE: {result['mse']:.6e}")
        print(f"  MAE: {result['mae']:.6e}")
        print(f"  Max Error: {result['max_error']:.6f}")
        print(f"  Match Rate: {result['match_rate']:.2f}%")
        print(f"  Status: {'PASSED' if result['passed'] else 'FAILED'}")
        print("=" * 60)

        # Show sample values if verbose
        if len(simulated_values) > 0:
            print(f"\nFirst 8 simulated values: {simulated_values[:8]}")
            print(f"First 8 golden values:    {list(golden[:8])}")

    return result


def save_golden_hbm(
    result: torch.Tensor,
    output_dir: Path,
    filename: str = "golden_hbm_result",
    elements_per_row: int = 32,
) -> dict:
    """Save golden HBM result in row-based format matching hbm_result.fp.txt.

    Args:
        result: Golden result tensor (can be any shape, will be flattened)
        output_dir: Directory to save files
        filename: Output filename base (without extension)
        elements_per_row: Number of elements per HBM row (default 32 for 256-bit rows with 8-bit elements)

    Returns:
        Dictionary with paths to saved files
    """
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    paths = {}

    # Flatten if needed
    flat_result = result.flatten()
    num_elements = len(flat_result)
    num_rows = (num_elements + elements_per_row - 1) // elements_per_row

    # Save as PyTorch tensor
    pt_path = output_dir / f"{filename}.pt"
    torch.save(result, pt_path)
    paths["pt"] = pt_path

    # Save in row-based format matching .mem file rows
    txt_path = output_dir / f"{filename}.txt"
    with open(txt_path, "w") as f:
        f.write("# Golden HBM Result\n")
        f.write(f"# Elements per HBM row: {elements_per_row}\n")
        f.write(f"# Rows: 0 to {num_rows - 1} (matching .mem file rows)\n")
        f.write(f"# Total elements: {num_elements}\n")
        f.write("#\n")
        for row_idx in range(num_rows):
            start_idx = row_idx * elements_per_row
            end_idx = min(start_idx + elements_per_row, num_elements)
            f.write(f"Row {row_idx:4d}:")
            for i in range(start_idx, end_idx):
                f.write(f" {flat_result[i].item():12.6f}")
            f.write("\n")
    paths["txt"] = txt_path

    return paths


def save_golden_vram(
    result: torch.Tensor,
    output_dir: Path,
    filename: str = "golden_vram_result",
    vlen: int = 16,
) -> dict:
    """Save golden VRAM result in row-based format matching vector_result.fp.txt.

    Args:
        result: Golden result tensor with shape (num_rows, vlen) or will be reshaped
        output_dir: Directory to save files
        filename: Output filename base (without extension)
        vlen: Number of elements per VRAM row

    Returns:
        Dictionary with paths to saved files
    """
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    paths = {}

    # Ensure 2D shape (num_rows, vlen)
    if result.dim() > 2:
        result = result.squeeze()
    if result.dim() == 1:
        num_elements = result.numel()
        num_rows = (num_elements + vlen - 1) // vlen
        result = result.flatten()
        # Pad if needed
        if num_elements < num_rows * vlen:
            result = torch.cat(
                [result, torch.zeros(num_rows * vlen - num_elements)]
            )
        result = result.view(num_rows, vlen)

    num_rows, actual_vlen = result.shape

    # Save as PyTorch tensor
    pt_path = output_dir / f"{filename}.pt"
    torch.save(result, pt_path)
    paths["pt"] = pt_path

    # Save in row-based format like vector_result.fp.txt
    txt_path = output_dir / f"{filename}.txt"
    with open(txt_path, "w") as f:
        f.write("# Golden VRAM Result\n")
        f.write(f"# VLEN: {actual_vlen}, Format: FP32\n")
        f.write(f"# Rows: 0 to {num_rows - 1}\n")
        f.write(f"# Total elements: {num_rows * actual_vlen}\n")
        f.write("#\n")
        for row_idx in range(num_rows):
            f.write(f"Row {row_idx:4d}:")
            for col_idx in range(actual_vlen):
                f.write(f" {result[row_idx, col_idx].item():12.6f}")
            f.write("\n")
    paths["txt"] = txt_path

    return paths


def main():
    """Main entry point for RTL simulation verification."""
    parser = argparse.ArgumentParser(
        description="Verify RTL simulation results against golden reference"
    )
    parser.add_argument(
        "--workload-dir",
        type=str,
        required=True,
        help="Path to workload build directory",
    )
    parser.add_argument(
        "--verbose", "-v", action="store_true", help="Print detailed output"
    )
    parser.add_argument(
        "--check-hbm",
        action="store_true",
        default=None,
        help="Check HBM contents (overrides params file)",
    )
    parser.add_argument(
        "--no-check-hbm",
        action="store_true",
        help="Disable HBM check (overrides params file)",
    )
    parser.add_argument(
        "--check-vram",
        action="store_true",
        default=None,
        help="Check VRAM contents (overrides params file)",
    )
    parser.add_argument(
        "--save-fp",
        action="store_true",
        default=True,
        help="Save FP-converted VRAM results to .fp.txt file (default: True)",
    )
    parser.add_argument(
        "--no-save-fp",
        action="store_true",
        help="Disable saving FP-converted results",
    )
    parser.add_argument(
        "--vlen",
        type=int,
        default=None,
        help="Override VLEN (elements per row)",
    )
    parser.add_argument(
        "--exp-width",
        type=int,
        default=None,
        help="Override V_FP_EXP_WIDTH (default: from params or 6)",
    )
    parser.add_argument(
        "--man-width",
        type=int,
        default=None,
        help="Override V_FP_MANT_WIDTH (default: from params or 5)",
    )
    parser.add_argument(
        "--check-rows",
        type=str,
        default=None,
        help="Check specific HBM rows (comma-separated, e.g., '0,1,2'). Uses row-based verification instead of full HBM check.",
    )
    parser.add_argument(
        "--expected",
        type=str,
        default="zeros",
        help="Expected values for row check: 'zeros' (default) or comma-separated floats",
    )
    parser.add_argument(
        "--atol",
        type=float,
        default=0.01,
        help="Absolute tolerance for comparison (default: 0.01)",
    )
    args = parser.parse_args()

    workload_dir = Path(args.workload_dir)

    # Load verification parameters
    params_file = workload_dir / "verification_params.json"
    if not params_file.exists():
        params_file = workload_dir / "comparison_params.json"

    if not params_file.exists():
        print(f"Error: No verification parameters file found in {workload_dir}")
        sys.exit(1)

    with open(params_file) as f:
        params = json.load(f)

    # Override params with command line arguments
    if args.vlen is not None:
        params["vlen"] = args.vlen
        params["row_dim"] = args.vlen
    if args.exp_width is not None:
        params["v_fp_exp_width"] = args.exp_width
    if args.man_width is not None:
        params["v_fp_man_width"] = args.man_width

    if args.verbose:
        print(f"Verification parameters loaded from: {params_file}")
        print(f"Workload type: {params.get('workload_type', 'unknown')}")
        if args.exp_width or args.man_width or args.vlen:
            print(
                f"Overrides: vlen={params.get('vlen')}, "
                f"exp_width={params.get('v_fp_exp_width')}, "
                f"man_width={params.get('v_fp_man_width')}"
            )

    results = {}
    all_passed = True
    save_fp = args.save_fp and not args.no_save_fp

    # HBM verification
    if args.check_rows:
        # Row-based verification (configurable)
        rows_to_check = [int(r.strip()) for r in args.check_rows.split(",")]

        # Parse expected values
        if args.expected == "zeros":
            expected_values = "zeros"
        else:
            try:
                expected_values = [
                    float(v.strip()) for v in args.expected.split(",")
                ]
            except ValueError:
                expected_values = "zeros"

        hbm_result = verify_hbm_rows(
            workload_dir,
            params,
            rows_to_check=rows_to_check,
            expected_values=expected_values,
            verbose=args.verbose,
            atol=args.atol,
        )
        results["hbm_rows"] = hbm_result
        if hbm_result.get("error") or not hbm_result.get("passed", False):
            all_passed = False

    else:
        # Determine if HBM check should run: CLI flag overrides params file
        if args.no_check_hbm:
            do_check_hbm = False
        elif args.check_hbm:
            do_check_hbm = True
        else:
            # No CLI flag specified, use params file (default True for backward compat)
            do_check_hbm = params.get("check_hbm", True)

        if do_check_hbm:
            # Full HBM verification (original method)
            hbm_result = verify_hbm(
                workload_dir,
                params,
                verbose=args.verbose,
                save_translated=save_fp,
            )
            results["hbm"] = hbm_result
            if hbm_result.get("error") or not hbm_result.get("passed", False):
                all_passed = False

    # VRAM verification: CLI flag overrides params file
    if args.check_vram is not None:
        do_check_vram = args.check_vram
    else:
        do_check_vram = params.get("check_vram", False)

    if do_check_vram:
        vram_result = verify_vram(
            workload_dir, params, verbose=args.verbose, save_fp_result=save_fp
        )
        results["vram"] = vram_result
        if vram_result.get("error") or not vram_result.get("passed", False):
            all_passed = False

    # Summary
    print("\n" + "=" * 60)
    print("Verification Summary")
    print("=" * 60)
    for check_type, result in results.items():
        if "error" in result:
            print(f"  {check_type.upper()}: ERROR - {result['error']}")
        else:
            status = "PASSED" if result.get("passed", False) else "FAILED"
            print(
                f"  {check_type.upper()}: {status} (match rate: {result.get('match_rate', 0):.2f}%)"
            )
            if "fp_output_file" in result:
                print(f"    FP results: {result['fp_output_file']}")
    print("=" * 60)
    print(f"Overall: {'PASSED' if all_passed else 'FAILED'}")
    print("=" * 60)

    sys.exit(0 if all_passed else 1)


if __name__ == "__main__":
    main()
