"""Linear layer workload generator for PLENA using the ATen compiler.

Generates test workloads for linear (dense) layer operations:
(batch, in_features) @ (in_features, out_features) -> (batch, out_features)

Uses PlenaCompiler from the aten compiler to generate ISA code.
"""

import argparse
import json
import sys
from pathlib import Path
from typing import Dict, Optional

import torch
from torch import Tensor

# Add necessary paths
_PROJECT_PATH = Path(__file__).resolve().parent.parent.parent
_TOOLS_PATH = _PROJECT_PATH / "tools"
if str(_TOOLS_PATH) not in sys.path:
    sys.path.insert(0, str(_TOOLS_PATH))

_PLENA_TOOLS_PATH = _PROJECT_PATH / "PLENA_Tools"
if str(_PLENA_TOOLS_PATH) not in sys.path:
    sys.path.insert(0, str(_PLENA_TOOLS_PATH))

_COMPILER_PATH = _PROJECT_PATH / "PLENA_Compiler"
if str(_COMPILER_PATH) not in sys.path:
    sys.path.insert(0, str(_COMPILER_PATH))

from .base import WorkloadGenerator
from cfl_tools import SRC_PATH
from sim_env_utils import create_mem_for_sim
from plena_utils.load_config import load_precision_from_svh, load_hardware_tile_sizes, get_quant_config_for_format
from plena_utils.config import calculate_instr_storage_offset_from_shapes, update_instruction_storage_offset
from verification import save_golden_vram

# Import assembly templates
from asm_templates import (
    preload_act_asm,
    preload_addr_reg_asm,
    reset_reg_asm,
    projection_asm,
    projection_T_asm,
)

# Import PlenaCompiler from the aten compiler (used when use_aten_compiler=True)
from compiler.aten.plena import PlenaCompiler

# Load hardware tile sizes from configuration.svh
_HW_TILE_SIZES = load_hardware_tile_sizes(SRC_PATH / "definitions")

# =============================================================================
# MX Format Configuration
# =============================================================================
DEFAULT_MX_FORMAT = None  # None means use precision.svh setting


class LinearWorkload(WorkloadGenerator):
    """Linear layer workload generator using ATen compiler.

    Generates test data for: (batch, in_features) @ (in_features, out_features)

    This generates:
    - Random input activation tensor
    - Random weight tensor
    - Golden result computed with quantized values
    - Assembly code generated by PlenaCompiler
    - Compiled machine code
    - HBM memory files in hex format
    """

    # Hardware tile sizes (loaded from configuration.svh)
    MLEN = _HW_TILE_SIZES["MLEN"]  # Matrix tile size
    BLEN = _HW_TILE_SIZES["BLEN"]  # Vector tile size
    VLEN = _HW_TILE_SIZES["VLEN"]  # Vector length
    HBM_V_Prefetch_Amount = _HW_TILE_SIZES["HBM_V_Prefetch_Amount"]  # Prefetch amount

    def __init__(
        self,
        batch_size: int = 4,
        in_features: int = 16,
        out_features: int = 32,
        mx_format: str = None,
        use_aten_compiler: bool = False,
        **kwargs,
    ):
        """Initialize linear workload generator.

        Args:
            batch_size: Batch size (must be divisible by BLEN)
            in_features: Input feature dimension (must be divisible by MLEN)
            out_features: Output feature dimension (must be divisible by MLEN)
            mx_format: MX format to use ("mxfp" or "mxint"). If None, uses DEFAULT_MX_FORMAT.
            use_aten_compiler: If True, use ATen PlenaCompiler. If False (default), use projection_asm template.
            **kwargs: Additional arguments passed to WorkloadGenerator
        """
        super().__init__(**kwargs)

        # Validate dimensions against hardware constraints
        assert batch_size % self.BLEN == 0, f"batch_size must be divisible by {self.BLEN}"
        assert in_features % self.MLEN == 0, f"in_features must be divisible by {self.MLEN}"
        assert out_features % self.MLEN == 0, f"out_features must be divisible by {self.MLEN}"

        self.batch_size = batch_size
        self.in_features = in_features
        self.out_features = out_features
        # Use provided format or fall back to module default
        self.mx_format = mx_format if mx_format is not None else DEFAULT_MX_FORMAT
        self.use_aten_compiler = use_aten_compiler

    def generate(self) -> dict:
        """Generate linear workload files using ATen compiler.

        Returns:
            Dictionary with paths to all generated files
        """
        self.build_dir.mkdir(parents=True, exist_ok=True)
        paths = self._init_memory_files()

        # Load precision settings and update quant_config based on mx_format
        precision_settings, config_settings = load_precision_from_svh(SRC_PATH / "definitions")
        actual_quant_config = get_quant_config_for_format(self.mx_format, precision_settings)
        self.quant_config = actual_quant_config  # Update the instance quant_config
        hbm_row_width = config_settings.get("HBM_WIDTH", 256)

        # 1. Generate random tensors
        activation = torch.randn(self.batch_size, self.in_features, dtype=torch.bfloat16)
        weight = torch.randn(self.in_features, self.out_features, dtype=torch.bfloat16)

        # 2. Quantize tensors using the same method as prefetch.py
        q_activation = self._quantize(activation)
        q_weight = self._quantize(weight)

        # 3. Compute golden result (using quantized values)
        golden_result = torch.matmul(q_activation.float(), q_weight.float())

        # 4. Save tensors for HBM staging
        # Order: activation first, then weight (matches specified_data_order)
        input_tensors = {
            "act_tensor": q_activation.to(torch.bfloat16),
            "weights": q_weight.to(torch.bfloat16),
        }
        tensor_paths = self._save_tensors(input_tensors)
        paths["tensors"] = tensor_paths

        # Save tensors as txt for debugging
        act_txt_path = self.build_dir / "act_tensor.txt"
        q_act_2d_debug = q_activation.reshape(self.batch_size, self.in_features).to(torch.float32)
        with open(act_txt_path, "w") as f:
            f.write(f"# Activation Tensor (quantized)\n")
            f.write(f"# Shape: ({self.batch_size}, {self.in_features})\n")
            for row_idx in range(self.batch_size):
                f.write(f"Row {row_idx:4d}:")
                for col_idx in range(self.in_features):
                    f.write(f" {q_act_2d_debug[row_idx, col_idx].item():12.6f}")
                f.write("\n")
        paths["act_txt"] = act_txt_path

        # 5. Calculate instruction offset based on tensor shapes
        tensor_shapes = [
            (self.batch_size, self.in_features),  # activation
            (self.in_features, self.out_features),  # weight
        ]
        instr_offset = calculate_instr_storage_offset_from_shapes(
            tensor_shapes, precision_settings, hbm_row_width
        )
        update_instruction_storage_offset(instr_offset, SRC_PATH / "definitions")

        # 6. Generate assembly code
        if self.use_aten_compiler:
            asm_code = self._generate_assembly_with_aten_compiler()
        else:
            asm_code = self._generate_assembly_with_template()
        asm_path = self.build_dir / "generated_asm_code.asm"
        asm_path.write_text(asm_code)
        paths["asm"] = asm_path

        # 7. Initialize FP and INT SRAM preload files
        from .utils.memory_format import write_fp_sram_hex, write_int_sram_hex
        fp_preload = [0.0, 1e-6, 1 / self.in_features]
        paths["fp_sram"] = write_fp_sram_hex(fp_preload, self.build_dir)
        paths["int_sram"] = write_int_sram_hex([0] * 10, self.build_dir)

        # 8. Use create_mem_for_sim to generate HBM memory files
        create_mem_for_sim(
            precision_settings=precision_settings,
            data_size=256,
            mode="behave_sim",
            asm="linear",
            data=None,
            specified_data_order=["act_tensor", "weights"],
            build_path=self.build_dir,
            hbm_row_width=hbm_row_width,
            mx_format=self.mx_format,
            instr_storage_offset=instr_offset,
        )

        paths["hbm"] = self.build_dir / "hbm.mem"
        paths["machine_code"] = self.build_dir / "generated_machine_code.mem"

        # 9. Save golden result
        golden_paths = self._save_golden(golden_result)
        paths["golden"] = golden_paths

        # Also save in detailed format
        golden_dict = {"input_tensor": input_tensors, "original_output": golden_result}
        with open(self.build_dir / "golden_result.txt", "w") as f:
            f.write(f"Linear: ({self.batch_size}, {self.in_features}) @ ({self.in_features}, {self.out_features})\n")
            f.write(f"Golden output shape: {list(golden_result.shape)}\n")
            f.write(f"Golden output:\n{golden_result}\n")

        # 9b. Generate VRAM golden for verification (first 8 rows)
        # Output shape: (batch_size, out_features)
        # VRAM layout: strided - (out_features // VLEN, batch_size, VLEN)
        golden_2d = golden_result.reshape(self.batch_size, self.out_features).to(torch.float32)
        # Reshape to (batch, out_features // VLEN, VLEN)
        golden_3d = golden_2d.reshape(self.batch_size, self.out_features // self.VLEN, self.VLEN)
        # Transpose to (out_features // VLEN, batch, VLEN) to match strided layout
        golden_transposed = golden_3d.permute(1, 0, 2)
        # Flatten to (total_vram_rows, VLEN)
        total_vram_rows = self.batch_size * (self.out_features // self.VLEN)
        golden_vram = golden_transposed.reshape(total_vram_rows, self.VLEN)
        vram_golden_paths = save_golden_vram(golden_vram, output_dir=self.build_dir, filename="golden_vram_result", vlen=self.VLEN)
        paths["golden_vram"] = vram_golden_paths

        # 9c. Save verification parameters for RTL simulation
        actual_format = self.quant_config.get("format", "mxfp")
        verification_params = {
            # Disable HBM verification
            "check_hbm": False,
            # VRAM verification params - check first 8 rows
            "check_vram": True,
            # Results land at result_base_address = batch*in_features elements
            # (= row 64 for the default shape); rows 0..63 hold the activations.
            "vram_start_row_idx": (self.batch_size * self.in_features) // self.VLEN,
            "vram_num_rows": 8,
            "row_dim": self.VLEN,
            "vram_compare_start_row": 0,
            "vram_compare_num_rows": 8,
            "vram_total_rows": total_vram_rows,
            "golden_vram_file": "golden_vram_result.pt",
            # General info
            "workload_type": "linear",
            "batch_size": self.batch_size,
            "in_features": self.in_features,
            "out_features": self.out_features,
            "output_shape": list(golden_result.shape),
            "mx_format": actual_format,
            "exp_width": self.quant_config["exp_width"],
            "man_width": self.quant_config["man_width"],
            "scale_width": self.quant_config["exp_bias_width"],
        }
        with open(self.build_dir / "verification_params.json", "w") as f:
            json.dump(verification_params, f, indent=2)
        paths["verification_params"] = self.build_dir / "verification_params.json"

        # 10. Save test parameters
        actual_format = self.quant_config.get("format", "mxfp")
        test_params = {
            "workload_type": "linear",
            "batch_size": self.batch_size,
            "in_features": self.in_features,
            "out_features": self.out_features,
            "mlen": self.MLEN,
            "blen": self.BLEN,
            "vlen": self.VLEN,
            "mx_format": actual_format,
            "exp_width": self.quant_config["exp_width"],
            "man_width": self.quant_config["man_width"],
            "scale_width": self.quant_config["exp_bias_width"],
            "seed": self.seed,
        }
        params_path = self.build_dir / "test_params.json"
        with open(params_path, "w") as f:
            json.dump(test_params, f, indent=2)
        paths["test_params"] = params_path

        # 11. Set environment variables
        self._set_env_vars(paths)

        return paths

    def _generate_assembly_with_aten_compiler(self) -> str:
        """Generate assembly code using PlenaCompiler from ATen compiler.

        Uses the same linear_projection API as used in the aten tests.

        Returns:
            Assembly code string
        """
        mlen = self.MLEN
        blen = self.BLEN
        real_data_ratio = (8 * 8 + 8) / (8 * 8)  # MXINT8 format ratio

        # Create PlenaCompiler instance
        prog = PlenaCompiler(
            mlen=mlen,
            blen=blen,
            real_data_ratio=real_data_ratio,
        )

        # Add header comment
        prog.emit(f"; Linear Test using ATen PlenaCompiler\n")
        prog.emit(f"; Shape: ({self.batch_size}, {self.in_features}) @ "
                  f"({self.in_features}, {self.out_features}) -> "
                  f"({self.batch_size}, {self.out_features})\n")
        prog.emit(f"; MLEN={mlen}, BLEN={blen}\n\n")

        # Declare inputs (activation and weight)
        # Activation: (batch_size, in_features) - pre-staged in VRAM at address 0
        act_input = prog.input(
            "X",
            shape=(self.batch_size, self.in_features)
        )

        # Weight: (in_features, out_features) - in HBM
        weight_input = prog.input(
            "W",
            shape=(self.in_features, self.out_features),
        )

        # Load activation from HBM to VRAM
        x = prog.load_batch(act_input, name="X")

        # Perform linear projection: Y = X @ W
        y = prog.linear_projection(x, weight_input, name="Y")

        # Note: Store back to HBM is disabled - result stays in VRAM for verification

        # Add break instruction at end
        prog.emit("\n; End of linear test\n")
        prog.emit("C_BREAK\n")

        # Compile and return the ISA code
        return prog.compile()

    def _generate_assembly_with_template(self) -> str:
        """Generate assembly code using projection_asm template.

        Uses the projection_asm template from asm_templates for the linear operation.

        Returns:
            Assembly code string
        """
        vlen = self.VLEN
        mlen = self.MLEN
        blen = self.BLEN
        preload_len = self.HBM_V_Prefetch_Amount
        real_data_ratio = (8 * 8 + 8) / (8 * 8)  # Account for scale overhead

        gen_assembly_code = "; Linear Test using projection_asm Template\n"
        gen_assembly_code += (
            f"; Shape: ({self.batch_size}, {self.in_features}) @ "
            f"({self.in_features}, {self.out_features}) -> "
            f"({self.batch_size}, {self.out_features})\n"
        )
        gen_assembly_code += f"; MLEN={mlen}, BLEN={blen}, VLEN={vlen}\n\n"

        # Calculate HBM offsets
        # Layout in HBM: [activations | weights]
        act_hbm_size = int(self.in_features * self.batch_size * real_data_ratio)

        # Set the addr offset for weight (needed for proper HBM addressing)
        gen_assembly_code += preload_addr_reg_asm(
            addr_reg_to_set=[1],
            available_registers=[1],
            addr_reg_val=[act_hbm_size]
        )

        # Reset the registers
        gen_assembly_code += reset_reg_asm(alive_registers=[1, 2, 3, 4, 5, 6])

        # Generate Activation Preload (HBM -> VRAM)
        gen_assembly_code += preload_act_asm(
            vlen=vlen,
            preload_len=preload_len,
            batch=self.batch_size,
            hidden_size=self.in_features,
            alive_registers=[1, 2, 3, 4, 5],
            act_vram_offset=0,
            activation_offset_reg=0,
            stride_size=self.in_features,
        )

        # Calculate VRAM addresses
        # Activations are at VRAM address 0
        activation_base_address = 0
        # Result goes after activations in VRAM
        result_base_address = self.batch_size * self.in_features

        # gen_assembly_code += "C_BREAK\n"
        # Generate projection (matrix multiply)
        gen_assembly_code += projection_asm(
            mlen=mlen,
            blen=blen,
            batch=self.batch_size,
            hidden_size=self.in_features,
            alive_registers=[1, 2, 3, 4, 5, 6],
            w_base_hbm_offset_reg=1,
            activation_base_address=activation_base_address,
            result_base_address=result_base_address,
            out_features=self.out_features,
        )

        # Add break instruction at end
        gen_assembly_code += "\n; End of linear test\n"
        gen_assembly_code += "C_BREAK\n"

        return gen_assembly_code

    def get_config(self) -> dict:
        """Get the workload configuration.

        Returns:
            Dictionary with configuration parameters
        """
        return {
            "workload_type": "linear",
            "batch_size": self.batch_size,
            "in_features": self.in_features,
            "out_features": self.out_features,
            "mlen": self.MLEN,
            "blen": self.BLEN,
            "quant_config": self.quant_config,
            "seed": self.seed,
            "mx_format": self.mx_format,
            "use_aten_compiler": self.use_aten_compiler,
        }


def main():
    """CLI entry point for linear workload generation."""
    parser = argparse.ArgumentParser(
        description="Generate linear layer workload for PLENA RTL simulation"
    )
    parser.add_argument(
        "--batch", type=int, default=8,
        help="Batch size (must be divisible by BLEN)"
    )
    parser.add_argument(
        "--in-features", type=int, default=128,
        help="Input feature dimension (must be divisible by MLEN)"
    )
    parser.add_argument(
        "--out-features", type=int, default=256,
        help="Output feature dimension (must be divisible by MLEN)"
    )
    parser.add_argument(
        "--build-dir", type=str, default=None,
        help="Output directory for generated files"
    )
    parser.add_argument(
        "--seed", type=int, default=42,
        help="Random seed for reproducibility"
    )
    parser.add_argument(
        "--mx-format", type=str, default=None, choices=["mxfp", "mxint"],
        help="MX format to use (mxfp or mxint). Default: use precision.svh settings"
    )
    parser.add_argument(
        "--use-aten-compiler", action="store_true",
        help="Use ATen PlenaCompiler instead of projection_asm template (default: use template)"
    )
    args = parser.parse_args()

    # Create workload generator
    workload = LinearWorkload(
        batch_size=args.batch,
        in_features=args.in_features,
        out_features=args.out_features,
        build_dir=args.build_dir,
        seed=args.seed,
        mx_format=args.mx_format,
        use_aten_compiler=args.use_aten_compiler,
    )

    # Generate files
    compiler_type = "ATen PlenaCompiler" if args.use_aten_compiler else "projection_asm template"
    print(f"Generating linear workload using {compiler_type}:")
    print(f"  Shape: ({args.batch}, {args.in_features}) @ ({args.in_features}, {args.out_features})")
    print(f"  Build dir: {workload.build_dir}")

    paths = workload.generate()

    print(f"\nGenerated files:")
    for key, value in paths.items():
        if isinstance(value, dict):
            for subkey, subvalue in value.items():
                print(f"  {key}/{subkey}: {subvalue}")
        else:
            print(f"  {key}: {value}")

    print(f"\nConfiguration:")
    config = workload.get_config()
    for key, value in config.items():
        print(f"  {key}: {value}")


if __name__ == "__main__":
    main()
