#!/usr/bin/env python3
"""Build compact benchmark and validation summaries from checked run outputs."""

from __future__ import annotations

import csv
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
RESULTS = Path(__file__).resolve().parent / "results"
REPORT = Path(__file__).resolve().parent / "fixed_balanced_latency_report.md"
CANONICAL_REPORT = (
    ROOT
    / "Workspace/reports/model_latency/qwen3_fixed_balanced_latency_report.md"
)


def _load(name: str) -> dict:
    return json.loads((RESULTS / name).read_text())


def _relative_error(predicted: float, reference: float) -> float:
    return 100.0 * abs(predicted - reference) / reference


def _write_markdown(rows: list[dict], validation: dict) -> None:
    """Render the checked JSON/CSV results as a self-contained evidence report."""

    lines = [
        "# Qwen3 Fixed-Balanced Unscheduled + V4 Latency Report",
        "",
        "## Scope",
        "",
        "This report evaluates a latency-only fixed-balanced routing mode for "
        "Qwen3-235B-A22B. It avoids materializing 61,696 static route objects "
        "for a 482 x 16 prefill while retaining router, dispatch, expert, "
        "combine, and physical HBM costs. The native compiler and transactional "
        "emulator remain static-index only.",
        "",
        "The common hardware configuration is MLEN=VLEN=512, BLEN=64, "
        "HLEN=128, M_LOAD=512, V_LOAD=V_WRITE=64, MXFP E4M3 block-8, "
        "128 HBM channels, and CLOCK_PERIOD_PS=1000. Decoder totals exclude "
        "lm_head. Qwen3-32B uses 64 layers; Qwen3-235B uses 94 repeated "
        "balanced histograms.",
        "",
        "## Estimator Design",
        "",
        "For fixed-balanced MoE, route counts are generated by "
        "expert(token, rank) = (token * top_k + rank) mod num_experts. "
        "At the target shape this gives 61,696 routes, 128 active experts, "
        "482 routes per expert, and 512 BLEN-padded rows per expert. Only the "
        "128-entry histogram is retained; exact token addresses and runtime "
        "arg-topk are intentionally excluded. Repeating this histogram over "
        "94 layers represents 5,799,424 decoder routes while still materializing "
        "zero Python route objects.",
        "",
        "The fast latency estimate is:",
        "",
        "```text",
        "stage_latency = max(stage_compute_resource_work, stage_v4_memory_work)",
        "total_latency = sum(stage_latency)",
        "serial_upper_bound = total_compute_work + total_v4_memory_work",
        "```",
        "",
        "A stage is a compiler semantic region, not one kernel. Examples are "
        "`layer/attention`, `layer/ffn`, `layer/moe/router`, "
        "`layer/moe/experts`, and `layer/moe/combine`; each can contain many "
        "kernels and opcodes. Summing one `max(compute, memory)` value per "
        "stage treats stage boundaries as serial. The resulting stage-wise "
        "roofline is therefore not a mathematical lower bound on the scheduled "
        "program: legal cross-stage overlap can make it conservative, while "
        "unmodeled hazards can make it optimistic on other workloads.",
        "",
        "Compute work uses the shared rtl-v1 opcode calibration. V4 memory "
        "work uses production DMA geometry. The fast path predicts one cold "
        "occurrence per geometry and scales its multiplicity. A global-row-state "
        "V4 pass is retained as a slower memory-only reference. Compressed "
        "Stage 2 replays ordered schedule repeats through the RTL scoreboard and "
        "is validation-only.",
        "",
        "## Runtime and Latency",
        "",
        "| Model | Scope | Cold wall (s) | Warm median (s) | Warm P95 (s) | Peak RSS (GiB) | Compute (ms) | V4 memory (ms) | Stage roofline (ms) | Serial bound (ms) |",
        "|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|",
    ]
    for row in rows:
        warm_median = row["warm_median_sec"]
        warm_p95 = row["warm_p95_sec"]
        lines.append(
            f"| {row['model']} | {row['scope']} | {row['cold_wall_sec']:.3f} | "
            f"{warm_median:.3f} | {warm_p95:.3f} | {row['peak_rss_gib']:.3f} | "
            f"{row['compute_resource_work_ms']:.3f} | "
            f"{row['v4_memory_work_ms']:.3f} | {row['stage_roofline_ms']:.3f} | "
            f"{row['serial_upper_bound_ms']:.3f} |"
        )

    lines.extend(
        [
            "",
            "Warm timings include process-local CostTrace and V4 work cache hits. "
            "Cold timings disable both caches. The target-scale fast path meets "
            "the requested <30 s cold, <1 s warm, and <2 GiB RSS limits.",
            "",
            "## Error Decomposition",
            "",
            "| Model | Cached V4 vs global V4 | Roofline vs compressed Stage 2 | Serial vs compressed Stage 2 | Stage 2 wall (s) | Stage 2 RSS (GiB) |",
            "|---|---:|---:|---:|---:|---:|",
        ]
    )
    for model in ("qwen3-32b", "qwen3-235b-a22b"):
        item = validation[model]
        lines.append(
            f"| {model} | {item['cached_v4_memory_error_percent']:.2f}% | "
            f"{item['stage_roofline_error_percent']:.2f}% | "
            f"{item['serial_upper_bound_error_percent']:.2f}% | "
            f"{item['stage2_wall_sec']:.2f} | {item['stage2_peak_rss_gib']:.3f} |"
        )

    holdout = validation["v4_generic_holdout"]
    seq1 = validation["qwen3_235b_seq1_static_transactional"]
    lines.extend(
        [
            "",
            "The cached-occurrence approximation changes one-layer V4 memory "
            "work by only 1.53% for 32B and 3.75% for 235B relative to the "
            "global-row-state evaluation. Both target cases are compute-bound, "
            "so the resulting stage-roofline change is much smaller than the "
            "memory-work percentage.",
            "",
            "The stage-roofline estimate is 18.53% high for 32B and 18.31% high "
            "for 235B relative to compressed Stage 2. This is scheduler omission "
            "error: coarse stage boundaries do not preserve all cross-stage "
            "overlap. It is not an absolute RTL error measurement. The serial "
            "sum is, as expected, a slightly looser upper bound.",
            "",
            "## Validation Evidence",
            "",
            "1. **Route conservation and compactness.** Unit tests verify 7,712 "
            "tokens x top-8 = 61,696 routes, a per-expert difference no greater "
            "than one, BLEN padding, stable semantic hashing, and the absence of "
            "a route-object list in the aggregate summary.",
            "2. **Static-plan parity.** A tiny Qwen3-MoE case compares fixed-balanced "
            "cost lowering with an explicit round-robin static plan. Dynamic "
            "opcode counts, per-stage opcode counts, and every compressed HBM "
            "event including geometry and multiplicity are exactly equal.",
            "3. **Scheduler parity with observed DMA.** The existing Qwen3-32B "
            "482 x 1 observed-DMA replay matches transactional makespan at "
            "25,452,302 cycles with zero cycle/stall/resource delta when supplied "
            "the same DMA completion sequence.",
            "4. **V4 generic holdout.** The production-DMA V4 holdout contains "
            f"{holdout['sample_count']} samples: median error "
            f"{holdout['median_absolute_error_percent']:.2f}%, P95 "
            f"{holdout['p95_absolute_error_percent']:.2f}%, weighted MAPE "
            f"{holdout['weighted_mape_percent']:.2f}%, maximum "
            f"{holdout['max_absolute_error_percent']:.2f}%, and store P95 "
            f"{holdout['store_p95_absolute_error_percent']:.2f}%.",
            "5. **MoE transactional chain.** The existing Qwen3-235B seq=1 "
            f"static-index run passes the unchanged numerical gate at "
            f"{seq1['comparison_match_rate_percent']:.1f}% and reports "
            f"{seq1['transactional_makespan_ns'] / 1e6:.3f} ms. Against that "
            f"run, CostEmitter serial work differs by {seq1['serial_error_percent']:.2f}%, "
            f"compressed Stage 2 by {seq1['stage2_error_percent']:.2f}%, and the "
            f"stage roofline by {seq1['roofline_error_percent']:.2f}%.",
            "6. **Focused regression.** The final dense CostEmitter, static-index "
            "MoE, fixed-balanced MoE, V4, and rtl-v1 scheduler suite completed "
            "61 tests with no failures.",
            "",
            "The seq=1 transactional case uses an explicit static expert set, "
            "not target-scale balanced routing. Equal-shaped experts make the "
            "cost invariant to expert IDs, and the tiny exact-parity test covers "
            "the round-robin aggregate transformation. No claim is made that "
            "balanced routing reproduces an input-dependent router distribution.",
            "",
            "## Interpretation",
            "",
            "Qwen3-235B has lower one-layer compute work than Qwen3-32B in this "
            "configuration because its active MoE width is top-8 x 1,536 = "
            "12,288, below the dense 32B intermediate width of 25,600. Its "
            "94-layer decoder estimate is nevertheless higher: 45.975 s versus "
            "36.281 s at the 1 GHz conversion assumption.",
            "",
            "For DSE, the stage-roofline estimate is fast enough for ordinary "
            "parallel trials and is preferable to compressed Stage 2, which took "
            "163-224 seconds per one-layer validation. The observed approximately "
            "18% conservative bias should be disclosed or corrected only after "
            "adding a held-out scheduler correction model; it should not be "
            "silently treated as cycle-exact latency.",
            "",
            "## Limitations",
            "",
            "- Fixed-balanced routing is a deterministic DSE assumption, not a "
            "prediction of real expert skew.",
            "- Runtime arg-topk is excluded because no current PLENA RTL/ISA "
            "implementation exists.",
            "- The 235B decoder repeats one balanced histogram across 94 layers "
            "and is marked approximate_repeated_balanced_routing.",
            "- V4 is a post-hoc service model; cached occurrence and global row "
            "state are both reported explicitly.",
            "- CLOCK_PERIOD_PS=1000 is a conversion assumption, not timing closure.",
            "- Decoder totals exclude lm_head, and compressed Stage 2 is a "
            "scheduler reference rather than absolute RTL silicon validation.",
            "",
            "## Artifacts",
            "",
            "- `results/latency_benchmark_summary.csv`",
            "- `results/latency_validation_summary.json`",
            "- `results/qwen3_32b_*` and `results/qwen3_235b_*` raw compact runs",
            "- `benchmark_fixed_balanced.py` and `build_report.py`",
            "",
        ]
    )
    rendered = "\n".join(lines)
    REPORT.write_text(rendered)
    CANONICAL_REPORT.parent.mkdir(parents=True, exist_ok=True)
    CANONICAL_REPORT.write_text(rendered)


def main() -> int:
    model_files = {
        "qwen3-32b": "qwen3_32b",
        "qwen3-235b-a22b": "qwen3_235b",
    }
    rows = []
    validation = {}
    for model, stem in model_files.items():
        one = _load(f"{stem}_one_layer_unscheduled_v4.json")
        full = _load(f"{stem}_full_unscheduled_v4.json")
        global_v4 = _load(f"{stem}_one_layer_global_v4.json")
        stage2 = _load(f"{stem}_one_layer_stage2.json")
        for scope, data in (("one_layer", one), ("full_decoder", full)):
            latency = data["latency"]
            runtime = data["runtime"]
            rows.append(
                {
                    "model": model,
                    "scope": scope,
                    "layers": data["num_layers"],
                    "cold_wall_sec": runtime["cold_wall_sec"],
                    "warm_median_sec": runtime["warm_median_sec"],
                    "warm_p95_sec": runtime["warm_p95_sec"],
                    "peak_rss_gib": runtime["peak_rss_kib"] / 1_048_576.0,
                    "compute_resource_work_ms": (
                        latency["compute_resource_work_ns"] / 1e6
                    ),
                    "v4_memory_work_ms": latency["v4_memory_work_ns"] / 1e6,
                    "stage_roofline_ms": latency["stage_roofline_ns"] / 1e6,
                    "serial_upper_bound_ms": (
                        latency["serial_upper_bound_ns"] / 1e6
                    ),
                    "routing_mode": data["routing"]["mode"],
                    "routing_fidelity": data["routing"]["fidelity"],
                }
            )
        cached_memory = one["latency"]["v4_memory_work_ns"]
        global_memory = global_v4["latency"]["v4_memory_work_ns"]
        roofline = one["latency"]["stage_roofline_ns"]
        serial = one["latency"]["serial_upper_bound_ns"]
        scheduled = stage2["latency"]["scheduled_shadow_ns"]
        validation[model] = {
            "cached_v4_memory_ns": cached_memory,
            "global_row_state_v4_memory_ns": global_memory,
            "cached_v4_memory_error_percent": _relative_error(
                cached_memory, global_memory
            ),
            "stage_roofline_ns": roofline,
            "serial_upper_bound_ns": serial,
            "compressed_stage2_ns": scheduled,
            "stage_roofline_error_percent": _relative_error(
                roofline, scheduled
            ),
            "serial_upper_bound_error_percent": _relative_error(
                serial, scheduled
            ),
            "stage2_wall_sec": stage2["runtime"]["cold_wall_sec"],
            "stage2_peak_rss_gib": (
                stage2["runtime"]["peak_rss_kib"] / 1_048_576.0
            ),
            "stage2_validation": stage2["latency"][
                "scheduled_shadow_validation"
            ],
        }

    with (RESULTS / "latency_benchmark_summary.csv").open("w", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=tuple(rows[0]))
        writer.writeheader()
        writer.writerows(rows)

    v4_validation = json.loads(
        (
            ROOT
            / "analytic_models/performance/calibration/hbm_dma_service_v4_validation.json"
        ).read_text()
    )
    validation["v4_generic_holdout"] = {
        **v4_validation["overall_holdout"],
        "store_p95_absolute_error_percent": v4_validation[
            "store_holdout_p95_absolute_error_percent"
        ],
    }
    transactional = json.loads(
        (
            ROOT
            / "Workspace/qwen3_235b_moe_compiler_smoke/target_real_fixed/rust_emulator_run_stats.json"
        ).read_text()
    )
    comparison = json.loads(
        (
            ROOT
            / "Workspace/qwen3_235b_moe_compiler_smoke/target_real_fixed/comparison_results.json"
        ).read_text()
    )
    validation["qwen3_235b_seq1_static_transactional"] = {
        "transactional_makespan_ns": transactional["sim_latency_ns"],
        "transactional_wall_sec": transactional["host_wall_time_seconds"],
        "comparison_allclose_pass": comparison["allclose_pass"],
        "comparison_match_rate_percent": comparison["match_rate"],
        # Compact values from the static-index CostEmitter shadow generated
        # from the same routing_plan.json and settings.  The full 35 MiB trace
        # remains a disposable /tmp diagnostic and is intentionally not copied.
        "costemitter_stage2_ns": 26_388_255.0,
        "costemitter_roofline_ns": 25_701_595.715281148,
        "costemitter_serial_ns": 30_270_918.366866335,
        "stage2_error_percent": _relative_error(
            26_388_255.0, transactional["sim_latency_ns"]
        ),
        "roofline_error_percent": _relative_error(
            25_701_595.715281148, transactional["sim_latency_ns"]
        ),
        "serial_error_percent": _relative_error(
            30_270_918.366866335, transactional["sim_latency_ns"]
        ),
    }
    (RESULTS / "latency_validation_summary.json").write_text(
        json.dumps(validation, indent=2, sort_keys=True) + "\n"
    )
    _write_markdown(rows, validation)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
